channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - jupyter
  - jupyter_client
  - jupyterlab
  - pip
  - black
  - pandas < 1.0
  - matplotlib
  - kedro==0.15.9
  - scikit-learn
  - seaborn
  - pip:
#      - -rrequirements.txt
      - pdbpp
