channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytest
  - ipython
  - jupyter
  - jupyter_client
  - jupyterlab
  - pytest-cov
  - pytest-mock
  - nbstripout
  - wheel
  - pip
  - gdal
  - black
  - pyproj
  - pandas < 1.0
  - matplotlib
  - kedro
  - pip:
      - -rrequirements.txt
      - pdbpp
